In [8]:
import statistics
import numpy as np
import scipy.stats as stats

In [2]:
li = [1,2,3,3]

In [3]:
statistics.mean(li)

2.25

In [4]:
np.mean(li)

2.25

In [5]:
np.median(li)

2.5

In [6]:
np.var(li)

0.6875

In [9]:
stats.mode(li)

C:\Users\USER\AppData\Local\Temp\ipykernel_18148\471236212.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(li)


ModeResult(mode=array([3]), count=array([2]))

In [11]:
one_d = np.random.randint(0,20, 20)    # Creating a one dimensional array with 20 items
one_d

array([ 0,  7, 15,  0,  1, 16, 15,  8,  5, 13,  8, 16,  4,  6,  0, 11,  7,
       11, 19, 16])

In [12]:
one_d.shape

(20,)

# Now I want to convert this 1 dimensional array to 2 dimensional array using reshape function (in 2 dim array there is 4 rows and 5 columns)

In [13]:
two_d = one_d.reshape(4,5)
two_d

array([[ 0,  7, 15,  0,  1],
       [16, 15,  8,  5, 13],
       [ 8, 16,  4,  6,  0],
       [11,  7, 11, 19, 16]])

In [14]:
np.mean(two_d)

8.9

# axis = 0 means Row but the meaning is across the rows these will give me 5 means of each column

In [15]:
np.mean(two_d, axis=0)

array([ 8.75, 11.25,  9.5 ,  7.5 ,  7.5 ])

## axis = 1 means Column but the meaning is across the columns these will give me 4 means of each rows

In [16]:
np.mean(two_d, axis=1)

array([ 4.6, 11.4,  6.8, 12.8])

# The variable two_d contains a 2 dimensional NumPy array that looks like:

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
Calculate the mean of each row. The final answer should be another NumPy array with 3 elements in it. Assign this to the variable answer

In [20]:
import numpy as np
two_d = np.arange(1, 10).reshape(3, 3)
two_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
answer = np.mean(two_d, axis=1)
answer

array([2., 5., 8.])

In [24]:
answer = two_d.mean(axis=1)
answer

array([2., 5., 8.])

# Calculate the mean of each column

In [22]:
answer = np.mean(two_d, axis=0)
answer

array([4., 5., 6.])

In [25]:
answer = two_d.mean(axis=0)
answer

array([4., 5., 6.])