In [1]:
import numpy as np

In [3]:
a = [1, 2, 3]

In [4]:
type(a)

list

In [5]:
b = np.array(a)
b

array([1, 2, 3])

In [6]:
type(b)

numpy.ndarray

In [7]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10)   ## This is a shortcut arange where a stand for array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,5, 6)

array([0., 1., 2., 3., 4., 5.])

In [12]:
np.linspace(0,3,31)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. ])

# Two dimensional array

In [13]:
c = [ [1, 2, 3], [10, 20, 30] ]
c

[[1, 2, 3], [10, 20, 30]]

In [14]:
type(c)

list

In [15]:
np.array(c)

array([[ 1,  2,  3],
       [10, 20, 30]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
first_thirty = np.linspace(0, 29, 30)
print(first_thirty)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]


In [21]:
first_thirty.reshape(3,10)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [22]:
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
reshaped_array = my_array.reshape(2,5)
print(reshaped_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
x_ax = np.linspace(-3.0, +3.0, 61)
print(x_ax)

[-3.  -2.9 -2.8 -2.7 -2.6 -2.5 -2.4 -2.3 -2.2 -2.1 -2.  -1.9 -1.8 -1.7
 -1.6 -1.5 -1.4 -1.3 -1.2 -1.1 -1.  -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3
 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1
  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5
  2.6  2.7  2.8  2.9  3. ]
