In [1]:
import numpy as np

In [2]:
first_ten = np.arange(0, 10)

In [3]:
first_ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
first_ten + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
first_ten - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [6]:
first_ten + first_ten

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
first_ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Assign the value 10 in the index zero

In [8]:
first_ten [0] = 10
first_ten

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [12]:
first_ten[:]

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [13]:
first_ten[6:]

array([6, 7, 8, 9])

In [14]:
first_ten[ : 4]

array([10,  1,  2,  3])

In [15]:
first_ten[:] = 10
first_ten

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [16]:
first_ten = np.arange(0, 10)
first_ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
first_five = first_ten[:5]
first_five

array([0, 1, 2, 3, 4])

In [19]:
first_five[:] = 0
first_five

array([0, 0, 0, 0, 0])

In [20]:
first_ten

array([0, 0, 0, 0, 0, 5, 6, 7, 8, 9])

In [23]:
np.random.seed(0)
data = np.random.randint(0, 100, 25).reshape((5, 5))
data

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72]])

In [26]:
scaled_data = data / 10
scaled_data

array([[4.4, 4.7, 6.4, 6.7, 6.7],
       [0.9, 8.3, 2.1, 3.6, 8.7],
       [7. , 8.8, 8.8, 1.2, 5.8],
       [6.5, 3.9, 8.7, 4.6, 8.8],
       [8.1, 3.7, 2.5, 7.7, 7.2]])