In [1]:
import  numpy as np

In [3]:
first_ten = np.arange(0,10)

In [4]:
first_ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
first_ten[3]

3

In [6]:
first_ten[3:5]

array([3, 4])

In [7]:
first_ten[ : 5]

array([0, 1, 2, 3, 4])

In [8]:
first_ten[6 : ]

array([6, 7, 8, 9])

In [9]:
first_thirty = np.linspace(0, 29, 30)
three_by_ten = first_thirty.reshape(3, 10)
print(three_by_ten.shape)

(3, 10)


In [10]:
three_by_ten

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [11]:
three_by_ten[1]

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [12]:
three_by_ten[1 , 5]

15.0

In [13]:
three_by_ten[0:3, 1:3]

array([[ 1.,  2.],
       [11., 12.],
       [21., 22.]])

In [14]:
tens = np.arange(0, 101, 10)

In [15]:
print(tens)

[  0  10  20  30  40  50  60  70  80  90 100]


In [16]:
tens >= 60

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [18]:
tens[tens >= 60]

array([ 60,  70,  80,  90, 100])

In [19]:
my_array = np.arange(0,10)

# Edit the following line
filtered_array = my_array[ my_array >4 ]
print(filtered_array)

[5 6 7 8 9]


In [20]:
data = np.arange(1, 41).reshape(4, 10)
data

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [21]:
my_slice = data[1:3, 3:7]
print(my_slice)

[[14 15 16 17]
 [24 25 26 27]]
